name: Test formulae

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false
      - uses: Homebrew/actions/setup-homebrew@a657b8b0cd35d0f65cce41fce9b24cf054b49869 # main
      - run: brew audit --strict synapt-dev/tap/gitgrip synapt-dev/tap/synapt
      - run: brew install synapt-dev/tap/gitgrip synapt-dev/tap/synapt
      - run: brew test synapt-dev/tap/gitgrip synapt-dev/tap/synapt
